---
roles:
 - src: https://github.com/moninca1234/ansible_ntp_role.git
   scm: git
   version: master
 
 - src: https://github.com/moninca1234/apache_ansible_role.git
   scm: git
   version: master


